@startuml activity
title Алгоритм обработки звонков

start
:Звонок клиента в компанию;
:Соединение со свободным оператором;

if (Постоянный клиент?) then (да)
    fork
        :Поиск клиента в CRM;
    fork again
        :Прием заявки;
    end fork
else (нет)
    :Информация об услугах и ценах;
    if (Интересно?) then (да)
        :Регистрация;
        :Прием заявки;
    else (нет)
        stop
    endif
endif

stop

@enduml