@startuml statechart
title Состояния заявки

[*] --> Новая : Пользователь создал заявку
Новая --> Согласуется : Заявка отправлена на согласование менеджеру
Согласуется --> Согласована : Менеджер \n согласовал заявку
Согласована --> Выполнена : Заявка исполнена
Выполнена --> [*]

Новая --> Отменена : Пользователь \n отменил заявку
Согласуется --> Отменена : Пользователь \n отменил заявку
Согласована --> Отменена : Пользователь \n отменил заявку
Отменена --> [*]

Новая --> Проблемная : [Время с момента \n создания > недели]
Проблемная --> Отменена : Заявка отменена \n пользователем или \n менеджером
@enduml